const myCurrencies = [{ name: '1inch Network', symbol: '1inch' },
  { name: 'Aave', symbol: 'aave' },
  { name: 'Cardano', symbol: 'ada' },
  { name: 'United Arab Emirates Dirham', symbol: 'aed' },
  { name: 'Afghan afghani', symbol: 'afn' },
  { name: 'Algorand', symbol: 'algo' },
  { name: 'Albanian lek', symbol: 'all' },
  { name: 'Armenian dram', symbol: 'amd' },
  { name: 'Synereo', symbol: 'amp' },
  { name: 'Netherlands Antillean Guilder', symbol: 'ang' },
  { name: 'Angolan kwanza', symbol: 'aoa' },
  { name: 'Arweave', symbol: 'ar' },
  { name: 'Argentine peso', symbol: 'ars' },
  { name: 'Atomic Coin', symbol: 'atom' },
  { name: 'Australian dollar', symbol: 'aud' },
  { name: 'Avalanche', symbol: 'avax' },
  { name: 'Aruban florin', symbol: 'awg' },
  { name: 'AXS', symbol: 'axs' },
  { name: 'Azerbaijani manat', symbol: 'azn' },
  { name: 'BakeryToken', symbol: 'bake' },
  { name: 'Bosnia-Herzegovina Convertible Mark', symbol: 'bam' },
  { name: 'Basic Attention Token', symbol: 'bat' },
  { name: 'Bajan dollar', symbol: 'bbd' },
  { name: 'Bitcoin Cash', symbol: 'bch' },
  { name: 'Bangladeshi taka', symbol: 'bdt' },
  { name: 'Bulgarian lev', symbol: 'bgn' },
  { name: 'Bahraini dinar', symbol: 'bhd' },
  { name: 'Burundian Franc', symbol: 'bif' },
  { name: 'Bermudan dollar', symbol: 'bmd' },
  { name: 'Binance Coin', symbol: 'bnb' },
  { name: 'Brunei dollar', symbol: 'bnd' },
  { name: 'Bolivian boliviano', symbol: 'bob' },
  { name: 'Brazilian real', symbol: 'brl' },
  { name: 'Bahamian dollar', symbol: 'bsd' },
  { name: 'Bitcoin SV', symbol: 'bsv' },
  { name: 'Biswap', symbol: 'bsw' },
  { name: 'Bitcoin', symbol: 'btc' },
  { name: 'Bitcoin BEP2', symbol: 'btcb' },
  { name: 'Bitcoin Gold', symbol: 'btg' },
  { name: 'Bhutan currency', symbol: 'btn' },
  { name: 'Binance USD', symbol: 'busd' },
  { name: 'Botswanan Pula', symbol: 'bwp' },
  { name: 'New Belarusian Ruble', symbol: 'byn' },
  { name: 'Belarusian Ruble', symbol: 'byr' },
  { name: 'Belize dollar', symbol: 'bzd' },
  { name: 'Canadian dollar', symbol: 'cad' },
  { name: 'PancakeSwap', symbol: 'cake' },
  { name: 'Congolese franc', symbol: 'cdf' },
  { name: 'Celo', symbol: 'celo' },
  { name: 'Swiss franc', symbol: 'chf' },
  { name: 'Chiliz', symbol: 'chz' },
  { name: 'Chilean peso', symbol: 'clp' },
  { name: 'Chinese Yuan', symbol: 'cny' },
  { name: 'Compound Coin', symbol: 'comp' },
  { name: 'Colombian peso', symbol: 'cop' },
  { name: 'Costa Rican Colón', symbol: 'crc' },
  { name: 'Crypto.com Chain Token', symbol: 'cro' },
  { name: 'Cravy', symbol: 'crv' },
  { name: 'Cuban peso', symbol: 'cuc' },
  { name: 'Cuban Peso', symbol: 'cup' },
  { name: 'Cape Verdean escudo', symbol: 'cve' },
  { name: 'Convex Finance', symbol: 'cvx' },
  { name: 'Czech koruna', symbol: 'czk' },
  { name: 'Dai', symbol: 'dai' },
  { name: 'Dash', symbol: 'dash' },
  { name: 'Decred', symbol: 'dcr' },
  { name: 'DfiStarter', symbol: 'dfi' },
  { name: 'Djiboutian franc', symbol: 'djf' },
  { name: 'Danish krone', symbol: 'dkk' },
  { name: 'Dogecoin', symbol: 'doge' },
  { name: 'Dominican peso', symbol: 'dop' },
  { name: 'Dotcoin', symbol: 'dot' },
  { name: 'Algerian dinar', symbol: 'dzd' },
  { name: 'Elrond', symbol: 'egld' },
  { name: 'Egyptian pound', symbol: 'egp' },
  { name: 'Enjin Coin', symbol: 'enj' },
  { name: 'EOS', symbol: 'eos' },
  { name: 'Eritrean nakfa', symbol: 'ern' },
  { name: 'Ethiopian birr', symbol: 'etb' },
  { name: 'Ethereum Classic', symbol: 'etc' },
  { name: 'Ether', symbol: 'eth' },
  { name: 'Euro', symbol: 'eur' },
  { name: 'Fei USD', symbol: 'fei' },
  { name: 'FileCoin', symbol: 'fil' },
  { name: 'Fijian dollar', symbol: 'fjd' },
  { name: 'Falkland Islands pound', symbol: 'fkp' },
  { name: 'Flow', symbol: 'flow' },
  { name: 'Frax', symbol: 'frax' },
  { name: 'Fantom', symbol: 'ftm' },
  { name: 'FarmaTrust', symbol: 'ftt' },
  { name: 'Gala', symbol: 'gala' },
  { name: 'Pound sterling', symbol: 'gbp' },
  { name: 'Georgian lari', symbol: 'gel' },
  { name: 'GGPro', symbol: 'ggp' },
  { name: 'Ghanaian cedi', symbol: 'ghs' },
  { name: 'Gibraltar pound', symbol: 'gip' },
  { name: 'Gambian dalasi', symbol: 'gmd' },
  { name: 'Guinean franc', symbol: 'gnf' },
  { name: 'Gnosis', symbol: 'gno' },
  { name: 'Golden Ratio Token', symbol: 'grt' },
  { name: 'GateToken', symbol: 'gt' },
  { name: 'Guatemalan quetzal', symbol: 'gtq' },
  { name: 'Guyanaese Dollar', symbol: 'gyd' },
  { name: 'Hedera', symbol: 'hbar' },
  { name: 'Hong Kong dollar', symbol: 'hkd' },
  { name: 'Honduran lempira', symbol: 'hnl' },
  { name: 'Helium', symbol: 'hnt' },
  { name: 'Hydro Protocol', symbol: 'hot' },
  { name: 'Croatian kuna', symbol: 'hrk' },
  { name: 'Huobi Token', symbol: 'ht' },
  { name: 'Haitian gourde', symbol: 'htg' },
  { name: 'Hungarian forint', symbol: 'huf' },
  { name: 'Internet Computer', symbol: 'icp' },
  { name: 'Indonesian rupiah', symbol: 'idr' },
  { name: 'Israeli New Shekel', symbol: 'ils' },
  { name: 'CoinIMP', symbol: 'imp' },
  { name: 'Injective', symbol: 'inj' },
  { name: 'Indian rupee', symbol: 'inr' },
  { name: 'Iraqi dinar', symbol: 'iqd' },
  { name: 'Iranian rial', symbol: 'irr' },
  { name: 'Icelandic króna', symbol: 'isk' },
  { name: 'Jersey Pound', symbol: 'jep' },
  { name: 'Jamaican dollar', symbol: 'jmd' },
  { name: 'Jordanian dinar', symbol: 'jod' },
  { name: 'Japanese yen', symbol: 'jpy' },
  { name: '', symbol: 'kas' },
  { name: 'Kava', symbol: 'kava' },
  { name: 'Kucoin', symbol: 'kcs' },
  { name: 'Kadena', symbol: 'kda' },
  { name: 'Kenyan shilling', symbol: 'kes' },
  { name: 'Kyrgystani Som', symbol: 'kgs' },
  { name: 'Cambodian riel', symbol: 'khr' },
  { name: 'Klaytn', symbol: 'klay' },
  { name: 'Comorian franc', symbol: 'kmf' },
  { name: 'Kyber Network', symbol: 'knc' },
  { name: 'North Korean won', symbol: 'kpw' },
  { name: 'South Korean won', symbol: 'krw' },
  { name: 'Kusama', symbol: 'ksm' },
  { name: 'Kuwaiti dinar', symbol: 'kwd' },
  { name: 'Cayman Islands dollar', symbol: 'kyd' },
  { name: 'Kazakhstani tenge', symbol: 'kzt' },
  { name: 'Laotian Kip', symbol: 'lak' },
  { name: 'Lebanese pound', symbol: 'lbp' },
  { name: 'LEOcoin', symbol: 'leo' },
  { name: 'ChainLink', symbol: 'link' },
  { name: 'Sri Lankan rupee', symbol: 'lkr' },
  { name: 'Loopring', symbol: 'lrc' },
  { name: 'Liberian dollar', symbol: 'lrd' },
  { name: 'Lesotho loti', symbol: 'lsl' },
  { name: 'Litecoin', symbol: 'ltc' },
  { name: 'Lithuanian litas', symbol: 'ltl' },
  { name: 'Luna Coin', symbol: 'luna' },
  { name: 'Latvian lats', symbol: 'lvl' },
  { name: 'Libyan dinar', symbol: 'lyd' },
  { name: 'Moroccan dirham', symbol: 'mad' },
  { name: 'Decentraland', symbol: 'mana' },
  { name: 'Polygon', symbol: 'matic' },
  { name: 'Moldovan leu', symbol: 'mdl' },
  { name: 'Malagasy ariary', symbol: 'mga' },
  { name: 'Mina', symbol: 'mina' },
  { name: 'IOTA', symbol: 'miota' },
  { name: 'Macedonian denar', symbol: 'mkd' },
  { name: 'Maker', symbol: 'mkr' },
  { name: 'Myanmar Kyat', symbol: 'mmk' },
  { name: 'Mongolian tugrik', symbol: 'mnt' },
  { name: 'Macanese pataca', symbol: 'mop' },
  { name: 'Mauritanian ouguiya', symbol: 'mro' },
  { name: 'Mauritian rupee', symbol: 'mur' },
  { name: 'Maldivian rufiyaa', symbol: 'mvr' },
  { name: 'Malawian kwacha', symbol: 'mwk' },
  { name: 'Mexican peso', symbol: 'mxn' },
  { name: 'Malaysian ringgit', symbol: 'myr' },
  { name: 'Mozambican Metical', symbol: 'mzn' },
  { name: 'Namibian dollar', symbol: 'nad' },
  { name: 'NEAR Protocol', symbol: 'near' },
  { name: 'NEO', symbol: 'neo' },
  { name: 'NEXO', symbol: 'nexo' },
  { name: 'Nigerian naira', symbol: 'ngn' },
  { name: 'Nicaraguan córdoba', symbol: 'nio' },
  { name: 'Norwegian krone', symbol: 'nok' },
  { name: 'Nepalese rupee', symbol: 'npr' },
  { name: 'New Zealand dollar', symbol: 'nzd' },
  { name: 'Okex', symbol: 'okb' },
  { name: 'Omani rial', symbol: 'omr' },
  { name: 'Menlo One', symbol: 'one' },
  { name: 'Panamanian balboa', symbol: 'pab' },
  { name: 'PAX Gold', symbol: 'paxg' },
  { name: 'Sol', symbol: 'pen' },
  { name: 'Papua New Guinean kina', symbol: 'pgk' },
  { name: 'Philippine peso', symbol: 'php' },
  { name: 'Pakistani rupee', symbol: 'pkr' },
  { name: 'Poland złoty', symbol: 'pln' },
  { name: 'Paraguayan guarani', symbol: 'pyg' },
  { name: 'Qatari Rial', symbol: 'qar' },
  { name: 'Quant', symbol: 'qnt' },
  { name: 'QTUM', symbol: 'qtum' },
  { name: 'Romanian leu', symbol: 'ron' },
  { name: 'Serbian dinar', symbol: 'rsd' },
  { name: 'Russian ruble', symbol: 'rub' },
  { name: 'THORChain (ERC20)', symbol: 'rune' },
  { name: 'Rwandan Franc', symbol: 'rwf' },
  { name: 'BeachCoin', symbol: 'sand' },
  { name: 'Saudi riyal', symbol: 'sar' },
  { name: 'Solomon Islands dollar', symbol: 'sbd' },
  { name: 'Seychellois rupee', symbol: 'scr' },
  { name: 'Sudanese pound', symbol: 'sdg' },
  { name: 'Swedish krona', symbol: 'sek' },
  { name: 'Singapore dollar', symbol: 'sgd' },
  { name: 'Shiba Inu', symbol: 'shib' },
  { name: 'Saint Helena pound', symbol: 'shp' },
  { name: '', symbol: 'sle' },
  { name: 'Sierra Leonean leone', symbol: 'sll' },
  { name: 'Sola', symbol: 'sol' },
  { name: 'Somali shilling', symbol: 'sos' },
  { name: 'Surinamese dollar', symbol: 'srd' },
  { name: 'São Tomé and Príncipe Dobra (pre-2018)', symbol: 'std' },
  { name: 'Stox', symbol: 'stx' },
  { name: 'Salvadoran Colón', symbol: 'svc' },
  { name: 'Syrian pound', symbol: 'syp' },
  { name: 'Swazi lilangeni', symbol: 'szl' },
  { name: 'Thai baht', symbol: 'thb' },
  { name: 'Theta', symbol: 'theta' },
  { name: 'Tajikistani somoni', symbol: 'tjs' },
  { name: 'Turkmenistani manat', symbol: 'tmt' },
  { name: 'Tunisian dinar', symbol: 'tnd' },
  { name: 'Tokamak Network', symbol: 'ton' },
  { name: 'Tongan Paʻanga', symbol: 'top' },
  { name: 'TRON', symbol: 'trx' },
  { name: 'Turkish lira', symbol: 'try' },
  { name: 'Trinidad & Tobago Dollar', symbol: 'ttd' },
  { name: 'Tap Project', symbol: 'ttt' },
  { name: 'True USD', symbol: 'tusd' },
  { name: 'New Taiwan dollar', symbol: 'twd' },
  { name: 'Tanzanian shilling', symbol: 'tzs' },
  { name: 'Ukrainian hryvnia', symbol: 'uah' },
  { name: 'Ugandan shilling', symbol: 'ugx' },
  { name: 'Universe', symbol: 'uni' },
  { name: 'United States dollar', symbol: 'usd' },
  { name: 'USD Coin', symbol: 'usdc' },
  { name: 'USDP Stablecoin', symbol: 'usdp' },
  { name: 'Tether', symbol: 'usdt' },
  { name: 'Uruguayan peso', symbol: 'uyu' },
  { name: 'Uzbekistani som', symbol: 'uzs' },
  { name: 'Sovereign Bolivar', symbol: 'vef' },
  { name: '', symbol: 'ves' },
  { name: 'Vechain', symbol: 'vet' },
  { name: 'Vietnamese dong', symbol: 'vnd' },
  { name: 'Vanuatu vatu', symbol: 'vuv' },
  { name: 'Waves', symbol: 'waves' },
  { name: 'Wrapped Bitcoin', symbol: 'wbtc' },
  { name: 'WEMIX', symbol: 'wemix' },
  { name: 'Samoan tala', symbol: 'wst' },
  { name: 'Central African CFA franc', symbol: 'xaf' },
  { name: 'Silver Ounce', symbol: 'xag' },
  { name: 'XauCoin', symbol: 'xau' },
  { name: 'East Caribbean dollar', symbol: 'xcd' },
  { name: 'Chia', symbol: 'xch' },
  { name: 'XDC Network', symbol: 'xdc' },
  { name: 'Special Drawing Rights', symbol: 'xdr' },
  { name: 'Eternal Coin', symbol: 'xec' },
  { name: 'NEM', symbol: 'xem' },
  { name: 'Stellar', symbol: 'xlm' },
  { name: 'Monero', symbol: 'xmr' },
  { name: 'West African CFA franc', symbol: 'xof' },
  { name: 'CFP franc', symbol: 'xpf' },
  { name: 'XRP', symbol: 'xrp' },
  { name: 'Tezos', symbol: 'xtz' },
  { name: 'Yemeni rial', symbol: 'yer' },
  { name: 'South African rand', symbol: 'zar' },
  { name: 'ZCash', symbol: 'zec' },
  { name: 'Zilliqa', symbol: 'zil' },
  { name: 'Zambian kwacha', symbol: 'zmk' },
  { name: 'Zambian Kwacha', symbol: 'zmw' },
  { name: 'Zimbabwean Dollar', symbol: 'zwl' },
];

export default myCurrencies;
